"""description not null

Revision ID: 9a1a2c548483
Revises: d54c604983e3
Create Date: 2026-07-22 12:20:03.170173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1a2c548483'
down_revision: Union[str, None] = 'd54c604983e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backfill any existing NULLs before tightening the constraint.
    op.execute("UPDATE tickets SET description = '' WHERE description IS NULL")
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
